# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:2.7.15-alpine3.8
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Build and push docker image
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            wget -O - https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz | tar xz -C /tmp
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker Image
          command: |
            docker build -t bruker2nifti .
      - deploy:
          name: Deploy Docker Image
          command: |
            if [ "$DOCKER_USER" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              if [ "$CIRCLE_TAG" ]; then
                docker tag bruker2nifti flywheel/bruker2nifti:${CIRCLE_TAG}
                docker push flywheel/bruker2nifti:${CIRCLE_TAG}
                (
                  IFS='.' read -ra VER_PARTS <<< "${CIRCLE_TAG}"
                  if [ "3" -eq "${#VER_PARTS[@]}" ]; then
                    MINOR_TAG="${VER_PARTS[0]}.${VER_PARTS[1]}"
                    docker tag bruker2nifti flywheel/bruker2nifti:${MINOR_TAG}
                    docker push flywheel/bruker2nifti:${MINOR_TAG}
                  fi
                )
              fi
              if [ "$CIRCLE_BRANCH" == "master" ]; then
                docker tag bruker2nifti flywheel/bruker2nifti:latest
                docker push flywheel/bruker2nifti:latest
              fi
            fi
